notifications:
  email: false

language: node_js

node_js:
  - 'node'

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn lint
  - yarn coverage

after_success:
  - yarn add --dev coveralls
  - cat coverage/lcov.info | npx coveralls
